### ISSUE TITLE
About authors

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#151] opened 2022-10-13 12:22 UTC
About http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/different-authors.html and authors, there are some weird things.

Why is the author medical decision in the section for "elementary" documents, but in the entries in "overview" documents? In CDA, they were both in the entries.

The reference types in the documentation (e.g. "_Author document & author medical decision: Composition.author -> Reference(CH EMED PractitionerRole | Device | CH Core Patient EPR | RelatedPerson)_") do not correspond to what is in the structure definitions. They could just be dropped from this page.

An author medical decision can't be a Device in the _different authors_ case, but it can be in the _one author_ case. That should not be authorized.

For the medication card, it's more complex. There's no concept of author medical decision and author original document, since it's a merge of all documents that possibly had different authors. The aggregator specifies the "last author" (author of the last entry for this treatment) and the "last medical author" (author of the last entry of type MTP, PRE or PADV except PADV COMMENT).
It fitted well in CDAs, but not so much in the current FHIR structure.

Edit: Also, authors are ..*, which is weird: "author" is generally singular in the page and it was ..1 in the CDAs.

**Comment by qligier** [comment] 2022-10-13 19:19
> PRE: there could be more than one entry, but a prescription should not have different practitioners listed as the author medical decision, so the section-level author makes sense in my view

That makes sense for the PRE, but I think it makes things worst in the PML: now we have to change the item author definition whether it's in the PML or not, which may imply creating PML-specific definitions of MedicationStatement, MedicationRequest, MedicationDispense and Observation if we want it to be clean.
The alternative is simply to move the authors from the section to the entry, which is only a problem in PRE documents. It's quite light, since it's only references, and we may create a constraint that check the reference of all MedicationRequests (can we?).

> Would the additional text (*) below the table for the CARD describe it so appropriately?

I would at least remove the ch-emed-ext-documentauthor extension, as it's the wrong concept. Then, whether we make `author` 1..2 or 2..2 (mimicking the CDAs, the index shows which author is what) or we add a "ch-emed-ext-last-medical-author" extension (and put the last author in `author`), I don't know.

**Comment by ziegm** [comment] 2022-10-14 06:52
> > PRE: there could be more than one entry, but a prescription should not have different practitioners listed as the author medical decision, so the section-level author makes sense in my view
> 
> That makes sense for the PRE, but I think it makes things worst in the PML: now we have to change the item author definition whether it's in the PML or not, which may imply creating PML-specific definitions of MedicationStatement, MedicationRequest, MedicationDispense and Observation if we want it to be clean. The alternative is simply to move the authors from the section to the entry, which is only a problem in PRE documents. It's quite light, since it's only references, and we may create a constraint that check the reference of all MedicationRequests (can we?).
> 
In the profiles (MedicationStatement, MedicationRequest, MedicationDispense and Observation), the description of the elements indicates that they are elements from CARD/LIST and a reference to the guidance is also added. 

> > Would the additional text (*) below the table for the CARD describe it so appropriately?
> 
> I would at least remove the ch-emed-ext-documentauthor extension, as it's the wrong concept. Then, whether we make `author` 1..2 or 2..2 (mimicking the CDAs, the index shows which author is what) or we add a "ch-emed-ext-last-medical-author" extension (and put the last author in `author`), I don't know.
>
The extension 'ch-emed-ext-documentauthor' was replaced with the CH Core Extension ([http://fhir.ch/ig/ch-core/StructureDefinition/ch-ext-author](https://build.fhir.org/ig/hl7ch/ch-core//StructureDefinition-ch-ext-author.html)). The guidance for CARD and LIST was adapted again and the use cases were expanded to support a better understanding.

**Comment by ziegm** [comment] 2022-10-14 06:53
The issue is on the agenda for the next meeting with @pjolo.

**Comment by qligier** [comment] 2022-10-14 08:52
I'm not sure I understand what would be the final result, is there a branch where I can see that?

**Comment by ziegm** [comment] 2022-10-14 08:56
It is (almost) everything on this Branch: http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/different-authors.html. Since we are only at the beginning of the resolution, not everything has been merged yet (that's why almost everything) and it is only a draft, which should be considered as a basis for discussion. Nothing has been discussed or even finally decided, so there is no final result yet.

**Comment by ziegm** [comment] 2022-10-25 16:27
@qligier 
We have discussed the changes with @pjolo  and the following changes have been made in the topic to the authors:
see [Change Log -> Different authors](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/changelog.html#added--updated)

The current status can be seen in the [ci build](http://build.fhir.org/ig/hl7ch/ch-emed/branches/master/index.html).

Could you give us feedback on this please.

**Comment by qligier** [comment] 2022-11-10 14:47
Seems good to me, except for these points:

* CH EMED MedicationStatement (LIST): `informationSource` should be _Reference(CH EMED PractitionerRole | CH Core Patient EPR | RelatedPerson)_ to match the composition section author.
* CH EMED Observation (LIST): same thing for the `performer`.

**Comment by ziegm** [comment] 2022-11-11 08:01
@qligier: Thank you for your input and review.

@pjolo: If you agree, we can close this issue.

**Comment by pjolo** [comment] 2022-11-17 07:35
For me, everything is ok and the issue can be closed.

**Closed** 2022-11-18 13:23 UTC
Labels: ready for review, authors
